### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by Culinarist** [erja/foorumi-api#2]
Projektin alussa yritin kokeilla Postmanillä uuden topic lisäämistä, mutta sequelizer ei voinut aukaista databasea. Tämän korjasin kun muunsin pathin database tiedostoon oikeaksi, jonka seurauksena löytyi toinen ongelma. Databasesta mikä projektissa löytyy ilmeisesti puuttuu Topics-taulu. Yritin sitä lisätä sinne perinteisillä CLI kutsuilla mitä ORM tarjoaa, mutta ilmeisesti projektista puuttui sequelizesta muutakin, en esimerkiksi löytänyt conffi tiedostoa mistään eikä pystynyt luomaan uusia malleja, seedejä tai tekemään migraatiota.

**Comment by erja** [comment]
Aina kannattaa liittää näihin ongelmatilanteisiin saatu virheilmoitus.
Jos yritän arvata: "Unhandled rejection SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous>"?
JOhtuu siitä, että tietokantaasi ei ole kirjoitusoikeuksia.
